# Generated by Django 3.0.6 on 2020-05-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0003_auto_20200512_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ebooks.Ebook'),
        ),
    ]
